apiVersion: batch/v1
kind: CronJob
metadata:
  name: curl
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  suspend: true
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 100
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: curl
              securityContext:
                readOnlyRootFilesystem: true
                runAsUser: 10001
              image: curlimages/curl:7.69.0
              command:
                - sh
                - -c
                - "curl -sL flagger.app/index.yaml | grep generated"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: curl-fail
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  suspend: true
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 100
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: curl
              securityContext:
                readOnlyRootFilesystem: true
                runAsUser: 10001
              image: curlimages/curl:7.69.0
              command:
                - sh
                - -c
                - "echo 'something went wrong' && curl -sL flagger.app | grep make-it-fail"
