name: ci

on:
  pull_request:
  push:
    branches:
      - master
    tags-ignore:
      - v.*

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Test
        run: make test
      - name: Build
        run: make build
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.20.0"
          image: "kindest/node:v1.27.3"
      - name: Integration test (job completed)
        run: |
          kubectl create ns test
          kubectl -n test apply -f examples/curl.yaml
          bin/kjob run -t curl -n test -c "echo testing"
      - name: Integration test (job failed)
        run: |
          if bin/kjob run -t curl-fail -n test; then
              exit 1
          fi
